### ISSUE TITLE
Reading Fortran namelist files without '.nml' extension

### ISSUE THREAD

**Issue by chx5** [jsta/nml#1]
Thank you for the `nml` package.
`read_nml()` cannot read Fortran namelist files without '.nml' extension.
In `utils.R`,
```
is_nml_file <- function(x){
 tools::file_ext(x) == "nml"
}
```

**Comment by ppernot** [comment]
I support this request, the file extension should not be a constraint.
Many fortran project have namelist files with other or no extentions...

**Comment by jsta** [comment]
Should work now. I downgraded the error message to a warning.

**Comment by ppernot** [comment]
Thanks !
