### ISSUE TITLE
Error in (blckOpen[i] + 1):(blckClse[i] - 1) : NA/NaN argument

### ISSUE THREAD

**Issue by adrfantini** [jsta/nml#2]
Thanks for this package!
It looks like it cannot read namelists like this one:
```
!
! DOMAIN dimension Stanza
!
 &dimparam
 iy     = 530,   ! This is number of points in the N/S direction
 jx     = 530,   ! This is number of points in the E/W direction
 kz     = 23,   ! Number of vertical levels
 dsmin  = 0.01, ! Minimum sigma spacing (only used if kz is not 14, 18, or 23)
 dsmax  = 0.05, ! Maximum sigma spacing (only used if kz is not 14, 18, or 23)
 nsg    = 1,    ! For subgridding, number of points to decompose. If nsg=1,
                ! no subgridding is performed. CLM does NOT work as of now with
                ! subgridding enabled.
 njxcpus = -1,  ! Number of CPUS to be used in the jx (lon) dimension.
                ! If <=0 , the executable will try to figure out a suitable
                ! decomposition.
 niycpus = -1,  ! Number of CPUS to be used in the iy (lat) dimension.
                ! If <=0 , the executable will try to figure out a suitable
                ! decomposition.
 /
!
! Choice of the dynamical core
!
 &coreparam
 idynamic = 1,  ! Choice of dynamical core
                ! 1 = MM4 hydrostatical core
                ! 2 = MM5 NON hydrostatical core
 /
```
This should be, as far as I know, a valid namelist. The error given is:
`Error in (blckOpen[i] + 1):(blckClse[i] - 1) : NA/NaN argument`

EDIT: it looks like it does not like spaces before the beginning (`&`) and end (`/`) characters of a stanza.

**Comment by jsta** [comment]
Thanks for the report. Happy for any help to fix this error. In the meantime, I recommend having a look at the `f90nml` python package which you can call from `R`: https://github.com/jsta/nml#using-the-f90nml-python-parser-via-the-reticulate-bridge

**Comment by adrfantini** [comment]
I think you could trim leading whitespace from `fileLines` when you define `lineStart`. One simple option is `lineStart	<-	substr(trimws(fileLines, which = 'left'),1,1)` or something along these lines (not tested). can do a PR if needed.
