### ISSUE TITLE
return original value and not NA if non-valid namelist entry

### ISSUE THREAD

**Issue by chrisdane** [jsta/nml#5]
Hi

This is a feature request.

The namlist entry
```
  key        = <value>
```
results in `NA` if loaded with `nml::read_nml()`. Would it be possible to return the character value `"<value>"` instead?

Thanks a lot and kind regards,
Chris

**Comment by jsta** [comment]
I would say almost certainly yes. Unfortunately, I don't work with nml files much anymore and can't devote time to development of the package. Happy to review pull request(s).

**Comment by jsta** [comment]
Is this solved by #6? @chrisdane

**Comment by chrisdane** [comment]
yes
